### ISSUE TITLE
what data frame to use?

### ISSUE THREAD

**Issue by abs8090** [uky-transport-data-science/ce599#16]
Hi, 
are we supposed to do the practice question on this data frame: 
`data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}?`

Thanks

**Comment by lwright139** [comment]
Yes but no. That is the correct data (some of the questions at the bottom refer to Ohio and Nevada) but the actual data frame from that data is defined as df (so you will type df instead of data in your answers).

**Comment by abs8090** [comment]
you're right, but I just wanted to know what data are we supposed to use
Thanks a lot Laura!!

**Comment by abs8090** [comment]
Another question please, what does "a profile" mean in the first two questions?
In other words, what are the first two question asking us to do?

**Comment by lwright139** [comment]
Gotcha, I just wasn't sure which part was tripping you up and wanted to make sure. :)

The statistical profile is just asking for a breakdown of the common statistics (mean, median, etc) or descriptive details of the column (in the case of question 2).
