### ISSUE TITLE
question about code shares

### ISSUE THREAD

**Issue by abs8090** [uky-transport-data-science/ce599#18]
in the homework 1 - code shares is says "do your best to identify which routes are code shares, and how many unique routes operate into/out of Lexington"

my question is, do we need to first find the routes that are code shares, then using this result find flights that go to/leave from Lexington?

Thanks

**Comment by gregerhardt** [comment]
I would probably do it the other way around--find all routes into/out of LEX, then look at those data and figure out which are real flights and which are code shares.

**Comment by abs8090** [comment]
Thank you Dr. Erhardt!!

Another question please, for the question "Identify which airports you can get to from Lexington with only one transfer." 
I noticed in the routes.dat file there are no flights with 'STOPS' higher than 0 leaving Lexington. 
Is that something expected since the dataset we have does not have the info we're looking for? or am I missing something here?

Thanks
