### ISSUE TITLE
next class homework

### ISSUE THREAD

**Issue by abs8090** [uky-transport-data-science/ce599#19]
Hi class, 

Hope you all are having a wonderful weekend. 
can anyone explain what needs to be done for the next class homework?

Thanks!

**Comment by gregerhardt** [comment]
Please have a look through the slides in lessons 11 and 12.  Do the following:

1. Choose one data source and one open-source code project that you find interesting/useful.  Come prepared to tell the class about it tomorrow.  
2. Choose one open API and figure out how to query it.  Tell us what you learned from this.
