### ISSUE TITLE
Assignment 7 Uber investigation

### ISSUE THREAD

**Issue by Kevin-Robert** [uky-transport-data-science/ce599#5]
here is a link the of code and what I think is relevant code to the problem
--
![assignment 7 error message](https://cloud.githubusercontent.com/assets/25165562/22792312/52a0eb3a-eeba-11e6-860d-f38fe88758f3.JPG)

--
thanks,
Kevin

**Comment by gregerhardt** [comment]
Looks like you have to sign up for an account and get a key.  Remember how we had the tokens for the twitter API?  This lets them keep track of who is using their data, and revoke the key if you don't follow the rules.
