### ISSUE TITLE
Reading .shp file into groupby

### ISSUE THREAD

**Issue by jdbr223** [uky-transport-data-science/ce599#7]
When I try to import the .shp file into jupyter notebook, I get an error that states "OSError: no such file or directory: 'gz_2010_21_140_00_500k.shp'."  I even verified that the file exists in the library.  
[JB_groupby code.zip](https://github.com/uky-transport-data-science/ce599-s17/files/791364/JB_groupby.code.zip)

**Comment by gregerhardt** [comment]
try data/gz_2010_21_140_00_500k.shp.  I think it is in a sub-directory, right?

**Comment by jdbr223** [comment]
Yes it is.  Took care of it.  Thanks again!
