### ISSUE TITLE
nx. ??

### ISSUE THREAD

**Issue by jdbr223** [uky-transport-data-science/ce599#9]
I am curious as to what nx. class is, because apparently this is what's used to calculate the shortest path, but there is no directory to pull it from.  It's in the code setup below to find the shortest path from my apartment to UK:

G = ox.graph_from_address('Fayette County, Kentucky', network_type='drive')
origin = ox.graph_from_address('3200 Todds Rd., Fayette County, Kentucky', network_type='drive')
destination = ox.graph_from_address('University of Kentucky', network_type='drive')
route = nx.shortest_path(G, origin, destination)
ox.plot_graph_route(G, route)

**Comment by gboeing** [comment]
nx refers to Python's [networkx](https://networkx.readthedocs.io/) package, which is typically imported like:

```python
import networkx as nx
```

[OSMnx](https://github.com/gboeing/osmnx) is built on top of networkx.
